# Site settings
title: Marco is live
email: m.phoebos@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello and Welcome. This is my second adventure on Jekyll.
  I find it so simple to span static sites. Ruby may be the reason why. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: marcoislive (not online yet)
github_username:  mphoebos

# Build settings
markdown: kramdown
